AthenaTools/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.url')),
    path('account/', include('User.url')),
]

DefaultProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.url')),
    path('account/', include('User.url')),
]

User/models.py
import string
import random

from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin, Group
from django.db import models
from django.utils import timezone


class AccountManager(BaseUserManager):

    def create_user(self, email, username, password, **other_fields):

        if not email:
            raise ValueError("Users must have an email address")
        if not username:
            raise ValueError("Users must have an unique username")

        email = self.normalize_email(email)
        user = self.model(username=username, email=email, **other_fields)
        user.set_password(password)
        user.save()

        return user

    def create_superuser(self, email, username, password, **other_fields):

        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)
        other_fields.setdefault('is_admin', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError('is_staff flag cannot be False')
        if other_fields.get('is_superuser') is not True:
            raise ValueError('is_superuser flag cannot be False')
        # Assign a random salary number for super user
        other_fields['salary_num'] = ''.join(random.choices(string.ascii_uppercase + string.digits, k=20))
        # Save the user model
        user = self.create_user(email, username, password, **other_fields)

        return user


class UserAccount(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=30, unique=True, verbose_name='Username')
    email = models.EmailField(max_length=60, unique=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    salary_num = models.CharField(max_length=30, unique=True, verbose_name='Salary Number')
    last_login = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=True, verbose_name='Status')
    is_moderator = models.BooleanField(default=False, verbose_name='Permissions')
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)
    is_superuser = models.BooleanField(default=False)
    projects = models.ManyToManyField('Project.Project', related_name='user_projects', blank=True)

    objects = AccountManager()
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username

User/forms.py
from crispy_bootstrap5.bootstrap5 import FloatingField
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Column, Row, Layout, Submit
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm, SetPasswordForm, PasswordChangeForm
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.urls import reverse

from Project.models import Project


class UserLoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'class': 'form-control', 'id': 'username'}))
    password = forms.CharField(required=True, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'id': 'password'}
    ))


class UserPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(UserPasswordResetForm, self).__init__(*args, **kwargs)

    email = forms.EmailField(required=True, widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': 'john.doe@example.com', 'type': 'email', 'name': 'email',
               'id': 'email', }))


class ChangePasswordForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

    new_password1 = forms.CharField(label='Password', required=True, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'id': 'new_password1'}
    ))

    new_password2 = forms.CharField(label='Confirm Password', required=True, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'id': 'new_password2'}
    ))


class ProfileChangePasswordForm(PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super(ProfileChangePasswordForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_class = 'needs-validation'
        self.helper.layout = Layout(
            Row(
                Column(FloatingField('old_password')),
            ),
            Row(

                Column(FloatingField('new_password1')),
            ),
            Row(
                Column(FloatingField('new_password2')),
            ),
            Row(
                Column(FormActions(Submit('change_password', 'Change Password'))),
            ),
        )


class CreateUserForm(forms.ModelForm):
    first_name = forms.CharField(label='Name')
    last_name = forms.CharField(label='Surname')
    salary_num = forms.CharField(label='Salary Number')
    password2 = forms.CharField(required=True, label='Confirm Password',
                                widget=forms.PasswordInput(attrs={'id': 'password'}))
    departments = forms.ModelChoiceField(required=True, queryset=Group.objects.all())
    is_moderator = forms.BooleanField(required=False, label='User is Moderator', widget=forms.CheckboxInput())

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password', 'first_name', 'last_name', 'is_moderator', 'salary_num')
        widgets = {'password': forms.PasswordInput(), }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')

        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        project_choices = [(x.project_code, x.project_name) for x in user.project_admin.all()]
        self.fields['projects'] = forms.MultipleChoiceField(required=True, choices=project_choices)
        group_choices = [(x.pk, x.name) for x in Group.objects.all()]
        self.fields['departments'] = forms.MultipleChoiceField(required=True, choices=group_choices)
        self.helper.form_method = 'post'
        self.helper.form_class = 'needs-validation'
        self.helper.form_action = reverse('create_new_user')
        self.helper.layout = Layout(
            Row(
                Column(FloatingField('username')),
                Column(FloatingField('email')),
                Column(FloatingField('salary_num')),
            ),
            Row(
                Column(FloatingField('password')),
                Column(FloatingField('password2')),
            ),

            Row(
                Column(FloatingField('first_name')),
                Column(FloatingField('last_name')),
            ),
            Row(
                Column(FloatingField('projects', css_class='h-100'), css_class='h-100'),
                Column(FloatingField('departments', css_class='h-100'), css_class='h-100'),
            ),
            Row(
                Column('is_moderator', css_class='text-start'),
            ),
            Row(
                Column(FormActions(Submit('submit', 'Add New User'))),
            ),
        )


class ProjectRemoveUserForm(forms.Form):

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        admin = kwargs.pop('admin')

        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.fields['project'] = forms.ModelChoiceField(label='Project', required=True,
                                                        queryset=user.project_users.filter(project_admin=admin).distinct())
        self.helper.form_class = 'needs-validation'
        self.helper.layout = Layout(
            Row(
                Column(FloatingField('project')),
            ),
        )

User/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import CreateView
from django.views.generic.edit import FormMixin, DeleteView
from django_filters.views import FilterView
from view_breadcrumbs import BaseBreadcrumbMixin

from Project.forms import CreateProjectForm
from Project.models import Project
from User.filters import ProjectUsersFilter
from User.forms import CreateUserForm, ProjectRemoveUserForm
from User.models import UserAccount


class CreateNewUser(LoginRequiredMixin, CreateView):
    form_class = CreateUserForm

    def get_form_kwargs(self):
        """
        Passes the required url parameter to the form (request.user object)
        """
        kwargs = super(CreateNewUser, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    # Redirect to this page after success
    def get_success_url(self):
        return reverse('management')

    def form_valid(self, form):
        # If both password fields match
        if form.cleaned_data['password'] == form.cleaned_data['password2']:
            form.save(commit=False)
            form.instance.set_password(form.cleaned_data['password'])
            user = form.save()
            # Add user to projects list selected from the choice field
            for project in form.cleaned_data['projects']:
                try:
                    proj = Project.objects.get(project_code=project)
                    user.projects.add(proj)
                    proj.users.add(user)
                except Project.DoesNotExist:
                    messages.error(self.request, 'Could not add user to the {name} project'.format(name=project))
                    return redirect('users_management')

            # Add user to department list selected from the choice field
            for department in form.cleaned_data['departments']:
                try:
                    group = Group.objects.get(pk=department)
                    group.user_set.add(user)
                except Group.DoesNotExist:
                    messages.error(self.request, 'Could not add user to the {name} department'.format(name=department))
                    return redirect('users_management')
            # Add a success message when User and Group objects are created
            messages.success(request=self.request, message='User added successfully!')
            return super().form_valid(form)

        # If both password fields do not match
        else:
            messages.error(self.request, 'Passwords do not match')
            return redirect('management')

    def form_invalid(self, form):

        for field, errors in form.errors.items():
            messages.error(self.request, '{}'.format(''.join(errors)))

        return redirect('management')


class ManagementView(LoginRequiredMixin, BaseBreadcrumbMixin, FormMixin, FilterView):
    model = UserAccount
    filterset_class = ProjectUsersFilter
    template_name = 'management_page.html'
    form_class = CreateUserForm
    crumbs = [("Admin Management", '')]
    context_object_name = 'users'
    paginate_by = 10

    def get_form_kwargs(self):
        """
        Passes the required url parameter to the form (request.user object)
        """
        kwargs = super(ManagementView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_queryset(self):
        """
        Prepare queryset for the Django Filters.
        :return: QuerySet of PipelineSpecs model
        """
        order_by = 'username'
        if self.request.GET.get('sort'):
            order_by = self.request.GET.get('sort')
        u = UserAccount.objects.get(pk=1)

        query_set = UserAccount.objects.filter(projects__project_admin=self.request.user).order_by(order_by).exclude(
            username=self.request.user.username).distinct()

        filter = self.filterset_class(self.request.GET, query_set)
        return filter.qs

    def get_context_data(self, **kwargs):
        context = super(ManagementView, self).get_context_data(**kwargs)

        unwanted_cols = ['id', 'logentry', 'project_users', 'password', 'user_permissions', 'is_active', 'is_staff',
                         'is_admin', 'date_joined', 'is_superuser', 'groups', 'users', 'project_admin']
        columns_list = [f.name for f in UserAccount._meta.get_fields() if f.name not in unwanted_cols]
        columns_verbose_name = [UserAccount._meta.get_field(col).verbose_name.title() for col in columns_list]

        context['columns'] = zip(columns_list, columns_verbose_name)
        context['add_user_form'] = CreateUserForm(user=self.request.user)
        context['projects_list'] = Project.objects.all()
        context['add_projects_form'] = CreateProjectForm

        return context


class DeleteUser(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = UserAccount
    success_message = 'User removed from project'

    def get_success_url(self):
        return reverse('management')

    def get(self, request, *args, **kwargs):
        user = UserAccount.objects.get(pk=self.kwargs['pk'])
        user_obj = user.__dict__

        fields = ['Username', 'Email', 'First Name', 'Last Name', 'Salary Number', 'Last Login']
        data_obj = [[UserAccount._meta.get_field(x).verbose_name.title(), y] for x, y in
                    zip(user_obj.keys(), user_obj.values()) if
                    x != '_state' and UserAccount._meta.get_field(x).verbose_name.title() in fields]

        user_projects_form = ProjectRemoveUserForm(user=user, admin=self.request.user)

        return render(request, 'partials/htmx/delete_modal.html', {'data_obj': data_obj,
                                                                   'obj_id': user.id,
                                                                   'user_projects_form': user_projects_form,
                                                                   'user_projects': Project.objects.all(),
                                                                   'delete_url': reverse('delete_user',
                                                                                         args=[user.id])})

    def form_valid(self, form):
        project = Project.objects.get(pk=self.request.POST['project'])
        user = UserAccount.objects.get(pk=self.kwargs['pk'])
        project.users.remove(user)
        user.projects.remove(project)
        messages.success(self.request,
                         'Successfully removed {} from project: {}'.format(user.username, project.project_name))
        return redirect(reverse('management'))

templates/User/create_user_form.html
<div class="row ">
    <div class="col-md ">
        <div id="div_id_username" class="form-floating mb-3">
            <input type="text" name="username" maxlength="30" class="textinput textInput form-control"
                   placeholder="username" required="" id="id_username">
            <label for="id_username">Username</label>
        </div>
    </div>
    <div class="col-md ">
        <div id="div_id_email" class="form-floating mb-3">
            <input type="email" name="email" maxlength="60" class="emailinput form-control" placeholder="email"
                   required="" id="id_email">
            <label for="id_email">Email</label>
        </div>
    </div>
    <div class="col-md ">
        <div id="div_id_salary_num" class="form-floating mb-3">
            <input type="text" name="salary_num" class="textinput textInput form-control" placeholder="salary_num"
                   required="" id="id_salary_num">
            <label for="id_salary_num">Salary Number</label>
        </div>
    </div>
</div>
<div class="row ">
    <div class="col-md ">
        <div id="div_id_password" class="form-floating mb-3"><input type="password" name="password" maxlength="128"
                                                                    class="textinput textInput form-control"
                                                                    placeholder="password" required="" id="id_password">
            <label for="id_password">Password</label>
        </div>
    </div>
    <div class="col-md ">
        <div id="div_id_password2" class="form-floating mb-3">
            <input type="password" name="password2" id="password" class="textinput textInput form-control"
                   placeholder="password2" required="">
            <label for="password">Confirm Password</label>
        </div>
    </div>
</div>
<div class="row ">
    <div class="col-md ">
        <div id="div_id_first_name" class="form-floating mb-3">
            <input type="text" name="first_name" class="textinput textInput form-control" placeholder="first_name"
                   required="" id="id_first_name">
            <label for="id_first_name">Name</label>
        </div>
    </div>
    <div class="col-md ">
        <div id="div_id_last_name" class="form-floating mb-3">
            <input type="text" name="last_name" class="textinput textInput form-control" placeholder="last_name"
                   required="" id="id_last_name">
            <label for="id_last_name">Surname</label>
        </div>
    </div>
</div>
<div class="row ">
    <div class="col-md text-start">
        <div class="mb-3">
            <div id="div_id_is_moderator" class="mb-3">
                <input type="checkbox" name="is_moderator" class="checkboxinput form-check-input" id="id_is_moderator">
                <label for="id_is_moderator" class="form-check-label">User is Moderator</label>
            </div>
        </div>
    </div>
</div>

templates/User/login.html
{% extends 'partials/registration/registration_forms.html' %}
{% block tile %}Login{% endblock %}
{% block form_title %}Login{% endblock %}
{% block errors %}
    {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            Incorrect username/password.
        </div>
    {% endif %}
{% endblock %}
{% block form_fields %}
    <div class="mb-3">
        <label class="mb-2 text-muted" for="username">Username</label>
        {{ form.username }}
        <div class="invalid-feedback">
            Username field cannot be blank
        </div>
    </div>

    <div class="mb-3">
        <div class="mb-2 w-100">
            <label class="text-muted" for="password">Password</label>
            <a href="{% url 'password_reset' %}" class="float-end">
                Forgot Password?
            </a>
        </div>
        {{ form.password }}
        <div class="invalid-feedback">
            Password field cannot be blank
        </div>
    </div>

    <div class="d-flex">
        <button type="submit" class="btn btn-primary">
            Login
        </button>
    </div>
{% endblock %}

templates/User/password_reset_complete.html
{% extends 'partials/registration/registration_forms.html' %}
{% block tile %}Password Reset Complete{% endblock %}
{% block form_title %}Password Reset Complete{% endblock %}
{% block form_fields %}
    <p>Your password has been successfully changed.</p>
    <p><a href="{% url 'login' %}">Click here</a> to login.</p>
{% endblock %}

templates/User/password_reset_confirm.html
{% extends "partials/registration/registration_forms.html" %}
{% block tile %}Password Reset{% endblock %}
{% block form_title %}
    Change Password
{% endblock %}
{% block errors %}
    {% if form.errors %}
        {% for field in form %}
           {% for error in field.errors %}
              <div class="alert alert-danger" role="alert">
                   {{ error|escape }}
              </div>
           {% endfor %}
       {% endfor %}
    {% endif %}
{% endblock %}
{% block form_fields %}
    {% if validlink %}
        <div class="mb-3">
            <label class="mb-2 text-muted" for="password1">Password</label>
            {{ form.new_password1 }}
            <div class="invalid-feedback">
                Password field cannot be blank
            </div>
        </div>

        <div class="mb-3">
            <div class="mb-2">
                <label class="text-muted" for="password2">Confirm Password</label>
            </div>
            {{ form.new_password2 }}
            <div class="invalid-feedback">
                Confirm Password field cannot be blank
            </div>
        </div>

        <div class="d-flex">
            <button type="submit" class="btn btn-primary">
                Submit
            </button>
        </div>
    {% else %}
        <p>The password reset link was invalid, possibly because it has already been used. Please request a <a
                href="{% url 'password_reset' %}">new password reset</a>.</p>
    {% endif %}

{% endblock %}

templates/User/password_reset_done.html
{% extends 'partials/registration/registration_forms.html' %}
{% block tile %}Password Reset{% endblock %}
{% block form_title %}Forgot Password{% endblock %}
{% block form_fields %}
    <p>Your request has been successfully registered. An email has been sent to the provided email address, please follow
        the instructions mentioned in the email.</p>
    <p><a href="{% url 'login' %}">Click here</a> to go back to login page.</p>
{% endblock %}

templates/User/password_reset_email.html
To reset your password for {{ email }}, please click on the link below:
{{ protocol}}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

templates/User/password_reset_form.html
{% extends 'partials/registration/registration_forms.html' %}
{% block tile %}Password Reset{% endblock %}
{% block form_title %}Forgot Password{% endblock %}
{% block errors %}
    {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {{ form.email.errors }}
        </div>
    {% endif %}
{% endblock %}
{% block form_fields %}
    <div class="mb-3">
        <label class="mb-2 text-muted" for="email">Email</label>
        {{ form.email }}
        <div class="invalid-feedback">
            Email field cannot be blank
        </div>
    </div>
    <div class="d-flex mb-3">
        <button type="submit" class="btn btn-primary">
            Reset Password
        </button>
    </div>
    <div class="d-flex">
        <a href="{% url 'login' %}">Go Back</a>
    </div>
{% endblock %}